### PR TITLE
don't show spinner when there is no handler to get children

### PR DESCRIPTION
**Pull request by amanulge**
https://github.com/PredixDev/px-context-browser/issues/11

Amanul Chowdhury(212393946)

### CODE REVIEW

**Comment by amanulge** [comment]
@runn-vermel There can be a case where there are no children for a certain context. and in that case it may not need to provide a getChildren handler.

**Comment by runn-vermel** [comment]
@amanulge to make sure i understand you - NONE of the options available have any children?

so, you provide an initial context, and NONE of the options have any children?

**Comment by amanulge** [comment]
@runn-vermel we do have a case like that where its just one level of context and none of them have childrens.

**Comment by davidrleonard** [comment]
We've released a new version of px-context-browser since this PR was submitted. Please take a look at that version.

**Pull request closed without merging**
