### PR TITLE
Added disabled functionality

### PR DESCRIPTION
**Pull request by 1mayur**
# Pull Request

Hi,

Thanks for helping us improve the Predix UI platform by submitting a Pull Request.

To help us merge your Pull Request as fast as possible, please fill out the following sections:

* ## A description of the changes proposed in the pull request: Added disabled functionality according to guideline set by design team

* ## A reference to a related issue (if applicable): https://github.com/PredixDev/px-context-browser/issues/22

* ## @mentions of the person or team responsible for reviewing proposed changes: @randyaskin

### CODE REVIEW

**Comment by randyaskin** [comment]
Looks great from a design perspective.

One thing, and this is probably a low risk issue, but if you set `disabled=true` and then set `show-column-browser=true`, the modal does still open and the user is able to edit the selected value. It's most obvious on the demo page when you use the toggles. I guess the way around this would be to create a new private copy of the boolean (`_show-column-browser`) which is computed based on `disabled` and use that for the logic instead? Open to other ideas.

**Comment by 1mayur** [comment]
@randyaskin Good catch, I've updated the PR with the fix. :)

**Comment by randyaskin** [comment]
Merged in v1.6.0. Thanks for the PR, nice work!

**Comment by 1mayur** [comment]
@randyaskin Thanks :)

**Pull request merged**
